riseupvpn experiment
ooni/probe-engine pull request #978
Opened 2020-10-13 09:00 UTC by cyBerta

* Implements connectivity tests for riseupvpn including provider API and gateways.
* Tests the reachability of openvpn and obfs4 ports of each gateway by performing a tcp handshake.
* Includes integration tests

2020-10-23 09:02 UTC, bassosimone requested changes
Thank you so much for working in this topic! This review accounts for around 50% of the pull request and specifically does not cover the test suite, which I could not look into in detail.

As an overall comment, the implementation here looks good. Most of my comments, suggestions, and request pertain to code style, consistency, and fixes.

My recommendation is for you to apply the requested changes while I continue my work of code review and take a more in depth look at the tests, run the code locally, etc.

I think it's reasonable to assume this process will converge in the next two weeks.

I also think we need to have a broader conversation on the scope of the experiment, its design, and its aims. But I also feel like it's important that a design discussion is anchored to running code and that it makes sense to move this prototype forward for informing the discussion.

Thanks again, keep up the good work! :guitar:

2020-10-24 14:05 UTC, cyBerta commented
Thanks for your review so far @bassosimone ! I'll adapt the PR accordingly to your comments.

2020-10-24 14:32 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn.go
> +	RiseupVPNApiFailure      *string             `json:"riseupvpn_api_failure"`
oh, it was inspired by tests for telegram, whatsapp, fbmanager. If Riseupvpn runs in the circumvention tools test suite together with tor and psiphon, would the scope still distinguishable?

2020-10-24 15:27 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn.go
> +		testkeys.RiseupVPNApiFailure = &errorValue
agreed

2020-10-24 15:29 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn.go
> +	multi = urlgetter.Multi{Begin: time.Now(), Getter: m.Getter, Session: sess}
Thanks for the hint. I fixed that

2020-10-24 15:30 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn.go
> +	return &eip, err
agreed. I took your suggestion

2020-10-24 15:31 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn.go
> +	urlgetter.RegisterExtensions(measurement)
Thanks, I fixed it

2020-10-24 15:32 UTC, cyBerta commented
besides the open question about the RiseupVPN prefix in variables and the missing spec description of the error values I adapted the PR accordingly.

2020-10-24 16:01 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn.go
> +		testkeys.RiseupVPNApiFailure = &errorValue
I added a PR: https://github.com/ooni/spec/pull/203

2020-10-25 09:55 UTC, bassosimone commented on experiment/riseupvpn/riseupvpn.go
> +	RiseupVPNApiFailure      *string             `json:"riseupvpn_api_failure"`
> oh, it was inspired by tests for telegram, whatsapp, fbmanager

Ah, my apologies, I didn't think about these specific keys in these experiments. I still have a feeling we don't need to add the `riseupvpn` prefix here. Going back, I'd not add any prefix to the IM experiment keys. We cannot change the past, but I think it's reasonable to use a more lean convention for this new experiment! 

> If Riseupvpn runs in the circumvention tools test suite together with tor and psiphon, would the scope still be distinguishable?

Yes: every experiment produces its own JSON document, therefore there is no ambiguity!

2020-10-25 10:24 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn.go
> +	RiseupVPNApiFailure      *string             `json:"riseupvpn_api_failure"`
> Yes: every experiment produces its own JSON document, therefore there is no ambiguity!

Great! I'll remove the prefex then.

2020-10-31 11:48 UTC, cyBerta commented
> Thank you for addressing my previous comments! I think there are two mains aspects of this diff that still need to be addressed, along with a bunch of minor nits. These aspects are:
> 
>     1. making sure we do not modify the global certificate pool (which should not have been exposed and which I'll make private soon)
> 
>     2. simplifying and possibly making more uniform the two tests in the test suite that deal with blocking of either "openvpn" or "obfs4" endpoints.
> 
> 
> Thanks again! +1

Thanks so much for your review again. 

I initially intended to set the CA certs only for the HTTP requests needed, as you described. Unfortunately I didn't (and still don't) see a possibility to set the generated cert pool to an urlgetter. I proposed a solution here: https://github.com/ooni/probe-engine/issues/1018#issuecomment-719922725. I would be interested if you see other already existing solutions to the problem.

2020-10-31 13:34 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn_test.go
> +			if transport.Type == "obfs4" {
You're right. Currently all gateways always support openvpn and it's always the first transport in the json array. But it's cleaner to filter for openvpn in TestIntegrationFailureOpenvpnGateway. :+1:

2020-10-31 15:23 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn_test.go
> +func TestIntegrationFailureOpenvpnGateway(t *testing.T) {
fixed by implementing subtests

2020-10-31 15:27 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn_test.go
> +		t.SkipNow()
I'm skipping all failures that are related to the precondition to the actual testing like fetching the CA cert in order to gather all necessary gateway information.

2020-10-31 15:27 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn_test.go
> +	if eipResponse.StatusCode == http.StatusOK {
fixed

2020-10-31 15:28 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn_test.go
> +	if caCertResponse.StatusCode == http.StatusOK {
fixed

2020-10-31 15:29 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn_test.go
> +	cancel()
fixed

2020-10-31 15:45 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn.go
> +// AddCACertFetchTestKeys Adding generic ctx.Get() testKeys to riseupvpn specific test keys
I fixed the comment

2020-11-05 00:16 UTC, cyBerta commented on experiment/riseupvpn/riseupvpn.go
> +	if ok := netx.CertPool.AppendCertsFromPEM([]byte(tk.HTTPResponseBody)); !ok {
I now create a local CertPool and append it to the urlgetter.Config.

2020-11-05 00:18 UTC, cyBerta commented
I think we're getting closer. Both issues you mentioned - about the certpool and about refactoring the tests - have been resolved.

2020-11-05 16:36 UTC, bassosimone commented
@cyBerta thank you! I've seen that [the tests failed](https://github.com/ooni/probe-engine/pull/978/checks?check_run_id=1355685856) with:

```
Error:     riseupvpn_test.go:83: unexpected FailingGateways value
```

Maybe a flaky hosts?

2020-11-05 16:37 UTC, bassosimone commented on experiment/riseupvpn/riseupvpn_test.go
> +		t.SkipNow()
Wouldn't this hide issues with the riseupvpn backend that instead we want to know about?

2020-11-06 13:12 UTC, bassosimone approved these changes
Thank you @cyBerta for your excellent work in this PR! I have run tests locally and they are working correctly. I'm going to merge this PR later today!

🐳

2020-11-06 13:22 UTC, merged

2020-11-06 19:11 UTC, cyBerta commented
Great! Thanks @bassosimone for your review. I'm happy to see the PR made it into probe-engine.