first (very crude) draft: miniooni http3 tests
ooni/probe-engine pull request #995
Opened 2020-10-23 13:02 UTC by kelmenhorst

2020-11-03 09:03 UTC, bassosimone requested changes
Thank you so much! This is very good work! I have requested a bunch of style changes and have pointed out that we need to sync up this branch with changes in OONI's master before we can proceed and merge the code. After this sync has occurred, we should also add a new test case that runs Go 1.15 along with Go 1.14 to have more confidence both cases are working. This can be done by creating a matrix in `workflows/shortttests.yml`.

Thanks again! 🎸

2020-11-03 10:43 UTC, kelmenhorst commented on netx/httptransport/http3transport.go
> +	}
Correct. This was just to show that it is possible to use custom dialers here. But you're right, practically, this is not useful currently.

2020-11-03 12:10 UTC, bassosimone commented on libminiooni/libminiooni.go
> +	}
Nice!

2020-11-03 12:12 UTC, bassosimone commented on netx/httptransport/http3transport.go
> +	}
Yeah, I think it has been useful to understand how to proceed and we can easily re-add later! Thanks!

2020-11-04 09:47 UTC, bassosimone approved these changes
Thank you so much @kelmenhorst, you have done an excellent work here! Looking forward to continue and experiment with `h3`. I'm now going to merge this branch!

🐳

2020-11-04 09:47 UTC, merged